---
title: "Using SQL to Query Data 2"
---

```{r}
#connecting to a database that is in the data folder

library(DBI)

filename <- "../data/prod_sample.db"
my_connection <- dbConnect(RSQLite::SQLite(),
                           dbname=filename)
my_connection
```

Activity 5:

```{sql connection=my_connection}
/* how many rows does the online_retail_history table contain */ 

select count(*) as number_rows 
from online_retail_history
```
```{sql connection=my_connection}
/* how many rows does the stock_description table contain */ 

select count(*) as number_rows 
from stock_description
```

```{sql connection=my_connection}
/* when was the first invoice*/ 

select MIN(InvoiceDate) as first_invoice 
from online_retail_history
```

```{sql connection=my_connection}
/* when was the last invoice*/ 

select MAX(InvoiceDate) as last_invoice 
from online_retail_history
```


```{sql connection=my_connection}
/* average price of good sold in the UK*/ 

select avg(Price) as avg_price_uk
from online_retail_history
where country = "United Kingdom"
```

```{sql connection=my_connection}
/* select CustomerID column*/ 

select CustomerID
from online_retail_history
```

```{sql connection=my_connection}
/* select the distinct (not repeated) CustomerIDs from CustomerID column*/ 

select distinct CustomerID
from online_retail_history
```


```{sql connection=my_connection}
/* count the number of distinct cutomers*/ 

select count(distinct CustomerID) as number_unique_customers
from online_retail_history
```
```{sql connection=my_connection}
/* count the unique number of customers per country*/ 

select Country, count(distinct CustomerID) as number_unique_customers
from online_retail_history
group by Country
```

```{sql connection=my_connection}
/* find the country wth the most number of disticnt customer ID*/ 

select Country
from online_retail_history
group by Country
order by count(distinct CustomerID) desc
limit 1
```

Activity 11 

```{sql connection=my_connection}
/* how many invoices does the online_retail_history table contain*/ 

select count(distinct Invoice) as distinct_invoices
from online_retail_history
```

```{sql connection=my_connection}
/* how many types of stocks were purchased*/ 

select count(distinct StockCode) as distinct_stocks
from online_retail_history
```

```{sql connection=my_connection}
/* how many types of stocks does the stock_description table contain*/ 

select count(distinct StockCode) as distinct_stocks
from stock_description
```

```{sql connection=my_connection}
/* how many stocks have "?" in the description*/ 

select count(distinct StockCode) as stocks_with_no_desc
from stock_description
where Description = "?"
```

```{sql connection=my_connection}
/* how many invoices have a negative quantity or price*/ 

select count(distinct Invoice) as negative_invoices
from online_retail_history
where quantity < 0 or price < 0
```

```{sql connection=my_connection}
/* what is the stock code of the most popular stock*/ 

select StockCode, sum(Quantity) as total_sum
from online_retail_history
group by StockCode
order by total_sum desc
limit 1
```

```{sql connection=my_connection}
/* what is the stock code of the most popular stock*/ 

select Description
from stock_description 
where StockCode = 22197
```
```{r}
#disconnect from a database
dbDisconnect(my_connection)
```

